[package]
name = "select-save"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = "symbols"
panic = "abort"
lto = "fat"
codegen-units = 1

[dependencies]
anyhow = "1.0.70"
chrono = "0.4.24"
clap = { version = "4.2.2", features = ["derive"] }
clap-verbosity-flag = "2.0.1"
env_logger = "0.10.0"
itertools = "0.10.5"
lazy_static = "1.4.0"
log = "0.4.17"
rand = "0.8.5"
regex = { version = "1.7.3", default-features = false, features = ["perf", "std"] }
sdl2 = { version = "0.35.2", features = ["ttf", "image"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
walkdir = "2.3.3"
