[package]
name = "select-save"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = "symbols"
panic = "abort"
lto = "fat"
codegen-units = 1

[profile.dev]
lto = "off"

[profile.dev.package."*"]
opt-level = 3
debug = 0

[profile.dev.package.select-save]
opt-level = 0
debug = 0

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.31"
clap = { version = "4.4.11", features = ["derive"] }
clap-verbosity-flag = "2.1.1"
env_logger = "0.10.1"
itertools = "0.12.0"
lazy_static = "1.4.0"
log = "0.4.20"
rand = "0.8.5"
regex = { version = "1.10.2", default-features = false, features = ["perf", "std"] }
sdl2 = { version = "0.36.0", features = ["ttf", "image"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
walkdir = "2.4.0"
